// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Anon key is public by design (protected by RLS). Hardcoded to avoid
// build-time env var issues with containerized deployments.
//
// SUPABASE_URL points at a same-origin nginx reverse proxy
// (sites-available/dkochnev → /supabase/* → mxttoiqtviaobotoekxw.supabase.co/*).
// We proxy because Russian ISPs intermittently block *.supabase.co; going
// via dkochnev.com (Selectel) makes the site usable without a VPN.
// Override with VITE_SUPABASE_URL=https://mxttoiqtviaobotoekxw.supabase.co
// for local dev that doesn't have the nginx proxy.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://dkochnev.com/supabase';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dHRvaXF0dmlhb2JvdG9la3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzNDQ0MjIsImV4cCI6MjA5MDkyMDQyMn0.bOmVtAGkUR6wY1ADfR3FtgP0f3CiFjcQs5WIp1LrKeI';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});